workflows:
  expo-ios:
    name: Expo iOS Build and Upload to TestFlight
    max_build_duration: 60
    environment:
      groups:
        - FACEMARK  
      vars:
        EAS_BUILD_PROFILE: "production"
      node: 16.20.0
      xcode: latest
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas login --token $EXPO_TOKEN
      - eas build --platform ios --profile $EAS_BUILD_PROFILE --non-interactive --no-wait
    artifacts:
      - build/**/*
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        api_key_id: $APP_STORE_CONNECT_API_KEY_ID
        api_issuer_id: $APP_STORE_CONNECT_API_ISSUER_ID
        submit_to_testflight: true
